import {
  H3ComfyError,
  buildH3FL2VGraph,
  buildH3I2VGraph,
  buildH3R2VGraph,
  framesForDuration,
  type ComfyUIClient,
  type H3Lora,
  type H3R2VLoader,
} from '@h3storyboard/h3-provider';
import {
  RelativeAssetPathSchema,
  type H3Job,
  type ProjectSnapshot,
} from '@h3storyboard/protocol';
import { createHash, randomUUID } from 'node:crypto';
import { mkdir, readFile, rename, rm, writeFile } from 'node:fs/promises';
import { basename, dirname, join, resolve, sep } from 'node:path';

export interface WorkerCompletionInput {
  name: string;
  relative_path: string;
  content_hash: string;
  observed_description: string;
}

export interface H3WorkerStore {
  recoverExpiredH3Jobs(now?: Date): number;
  claimNextH3Job(leaseDurationMs?: number): H3Job | null;
  getProjectSnapshot(projectId: string): ProjectSnapshot;
  markH3JobQueued(jobId: string, leaseToken: string,
    providerJobId: string): H3Job;
  markH3JobRunning(jobId: string, leaseToken: string): H3Job;
  heartbeatH3Job(jobId: string, leaseToken: string,
    leaseDurationMs?: number): H3Job;
  failH3Job(jobId: string, leaseToken: string, errorCode: string,
    errorMessage: string): H3Job;
  cancelH3Job(jobId: string, reason?: string): H3Job;
  finalizeWorkerOutput(jobId: string, leaseToken: string,
    input: WorkerCompletionInput): unknown;
}

export interface H3LeaseWorkerOptions {
  store: H3WorkerStore;
  client: ComfyUIClient;
  data_directory: string;
  lease_duration_ms?: number;
  idle_interval_ms?: number;
  width?: number;
  height?: number;
  fps?: number;
  turbo?: boolean;
  loras?: readonly H3Lora[];
  generate_audio?: boolean;
  free_before_submit?: boolean;
  r2v_loader?: H3R2VLoader;
  on_error?: (error: unknown) => void;
}

export type H3WorkerRunResult =
  | { outcome: 'idle' }
  | { outcome: 'completed'; job_id: string; provider_task_id: string;
    output_path: string }
  | { outcome: 'failed'; job_id: string; error_code: string;
    error_message: string };

export class H3LeaseWorker {
  readonly #options: Required<Omit<H3LeaseWorkerOptions,
    'loras' | 'on_error'>> & Pick<H3LeaseWorkerOptions, 'on_error'> &
    { loras: readonly H3Lora[] };
  #stopping = false;
  #loop: Promise<void> | null = null;

  constructor(options: H3LeaseWorkerOptions) {
    this.#options = {
      ...options,
      data_directory: resolve(options.data_directory),
      lease_duration_ms: options.lease_duration_ms ?? 60 * 60_000,
      idle_interval_ms: options.idle_interval_ms ?? 1_000,
      width: options.width ?? 480,
      height: options.height ?? 864,
      fps: options.fps ?? 24,
      turbo: options.turbo ?? true,
      loras: options.loras ?? [],
      generate_audio: options.generate_audio ?? true,
      free_before_submit: options.free_before_submit ?? true,
      r2v_loader: options.r2v_loader ?? { kind: 'stock' },
    };
  }

  async runOnce(): Promise<H3WorkerRunResult> {
    this.#options.store.recoverExpiredH3Jobs();
    const job = this.#options.store.claimNextH3Job(
      this.#options.lease_duration_ms);
    if (!job) return { outcome: 'idle' };
    const leaseToken = job.lease_token!;
    let outputPath: string | null = null;
    try {
      const providerTaskId = job.provider_job_id ?? await this.#submit(job);
      this.#options.store.markH3JobQueued(job.id, leaseToken, providerTaskId);
      this.#options.store.markH3JobRunning(job.id, leaseToken);
      this.#options.store.heartbeatH3Job(job.id, leaseToken,
        this.#options.lease_duration_ms);
      const history = await this.#options.client.pollHistory(providerTaskId);
      this.#options.store.heartbeatH3Job(job.id, leaseToken,
        this.#options.lease_duration_ms);
      const item = this.#options.client.firstOutput(history);
      const bytes = await this.#options.client.downloadOutput(item);
      const written = await this.#writeOutput(job, bytes);
      outputPath = written.absolutePath;
      this.#options.store.finalizeWorkerOutput(job.id, leaseToken, {
        name: basename(written.relativePath),
        relative_path: written.relativePath,
        content_hash: written.contentHash,
        observed_description: `Generated by ${job.provider} task ${providerTaskId}`,
      });
      return { outcome: 'completed', job_id: job.id,
        provider_task_id: providerTaskId, output_path: written.relativePath };
    } catch (error) {
      if (outputPath) await rm(outputPath, { force: true }).catch(() => undefined);
      const failure = workerFailure(error);
      try {
        this.#options.store.failH3Job(job.id, leaseToken,
          failure.code, failure.message);
      } catch (failError) {
        this.#options.on_error?.(failError);
      }
      return { outcome: 'failed', job_id: job.id,
        error_code: failure.code, error_message: failure.message };
    }
  }

  cancel(jobId: string, reason: string): H3Job {
    return this.#options.store.cancelH3Job(jobId, reason);
  }

  start(): void {
    if (this.#loop) return;
    this.#stopping = false;
    this.#loop = this.#runLoop();
  }

  async stop(): Promise<void> {
    this.#stopping = true;
    await this.#loop;
    this.#loop = null;
  }

  async #submit(job: H3Job): Promise<string> {
    if (job.mode !== 'i2v' && job.mode !== 'fl2v' && job.mode !== 'r2v') {
      throw new H3WorkerError('H3_WORKER_MODE_UNSUPPORTED',
        'H3 worker supports i2v, fl2v, and r2v jobs');
    }
    if (job.seed === null) throw new H3WorkerError(
      'H3_WORKER_SEED_REQUIRED', 'H3 worker jobs require a persisted seed');
    const bindings = job.mode === 'r2v' ? [...(job.compiled_bindings ?? [])] :
      ['first_frame', ...(job.mode === 'fl2v' ? ['last_frame'] : [])].map(
        (purpose) => job.compiled_bindings?.find((binding) =>
          binding.purpose === purpose));
    if (bindings.length === 0 || bindings.some((binding) => !binding)) {
      throw new H3WorkerError('H3_WORKER_INPUT_MISSING',
        `Compiled ${job.mode} job has no required image inputs`);
    }
    const images: Array<{ path: string; bytes: Buffer }> = [];
    for (const binding of bindings) {
      const path = safeDataPath(this.#options.data_directory, binding!.uri);
      let bytes: Buffer;
      try { bytes = await readFile(path); }
      catch (error) { throw new H3WorkerError('H3_WORKER_INPUT_READ_FAILED',
        'Could not read a compiled image asset', { cause: error }); }
      if (bytes.byteLength === 0) throw new H3WorkerError(
        'H3_WORKER_INPUT_EMPTY', 'Compiled image asset is empty');
      images.push({ path, bytes });
    }
    if (this.#options.free_before_submit) await this.#options.client.free();
    const names: string[] = [];
    for (const image of images) names.push(await this.#options.client.uploadImage(
      new Blob([Uint8Array.from(image.bytes)]), basename(image.path)));
    const common = { prompt: job.prompt, width: this.#options.width,
      height: this.#options.height,
      frames: framesForDuration(job.duration_seconds, this.#options.fps),
      fps: this.#options.fps, seed: job.seed, loras: this.#options.loras,
      steps: job.steps, turbo: this.#options.turbo,
      filename_prefix: `h3storyboard/${job.id}`,
      generate_audio: this.#options.generate_audio,
    };
    const graph = job.mode === 'i2v'
      ? buildH3I2VGraph({ ...common, start_name: names[0]! })
      : job.mode === 'fl2v'
        ? buildH3FL2VGraph({ ...common, start_name: names[0]!,
          end_name: names[1]! })
        : buildH3R2VGraph({ ...common, reference_names: names,
          loader: this.#options.r2v_loader });
    return this.#options.client.submitPrompt(graph);
  }

  async #writeOutput(job: H3Job, bytes: Uint8Array) {
    const relativePath = `projects/${job.project_id}/outputs/${job.id}.mp4`;
    const absolutePath = safeDataPath(this.#options.data_directory, relativePath);
    const temporaryPath = `${absolutePath}.${randomUUID()}.tmp`;
    await mkdir(dirname(absolutePath), { recursive: true });
    try {
      await writeFile(temporaryPath, bytes, { flag: 'wx' });
      await rename(temporaryPath, absolutePath);
    } catch (error) {
      await rm(temporaryPath, { force: true }).catch(() => undefined);
      throw new H3WorkerError('H3_WORKER_OUTPUT_WRITE_FAILED',
        'Could not persist the downloaded H3 output', { cause: error });
    }
    return { relativePath, absolutePath,
      contentHash: `sha256:${createHash('sha256').update(bytes).digest('hex')}` };
  }

  async #runLoop(): Promise<void> {
    while (!this.#stopping) {
      try { await this.runOnce(); }
      catch (error) { this.#options.on_error?.(error); }
      if (!this.#stopping) await delay(this.#options.idle_interval_ms);
    }
  }
}

export type H3WorkerErrorCode =
  | 'H3_WORKER_MODE_UNSUPPORTED'
  | 'H3_WORKER_SEED_REQUIRED'
  | 'H3_WORKER_INPUT_MISSING'
  | 'H3_WORKER_INPUT_READ_FAILED'
  | 'H3_WORKER_INPUT_EMPTY'
  | 'H3_WORKER_OUTPUT_WRITE_FAILED'
  | 'H3_WORKER_PATH_INVALID'
  | 'H3_WORKER_FAILED';

export class H3WorkerError extends Error {
  constructor(readonly code: H3WorkerErrorCode, message: string,
    options?: ErrorOptions) {
    super(message, options);
    this.name = 'H3WorkerError';
  }
}

function safeDataPath(dataDirectory: string, relativePath: string): string {
  const parsed = RelativeAssetPathSchema.safeParse(relativePath);
  if (!parsed.success) throw new H3WorkerError('H3_WORKER_PATH_INVALID',
    'Worker asset path must remain project-relative');
  const absolute = resolve(dataDirectory, parsed.data);
  if (!absolute.startsWith(`${dataDirectory}${sep}`)) throw new H3WorkerError(
    'H3_WORKER_PATH_INVALID', 'Worker asset path escaped the data directory');
  return absolute;
}

function workerFailure(error: unknown): { code: string; message: string } {
  if (error instanceof H3ComfyError || error instanceof H3WorkerError) {
    return { code: error.code, message: error.message.slice(0, 2_000) };
  }
  if (typeof error === 'object' && error !== null &&
    typeof (error as { code?: unknown }).code === 'string') {
    return { code: (error as { code: string }).code,
      message: error instanceof Error ? error.message.slice(0, 2_000) : 'Worker failed' };
  }
  return { code: 'H3_WORKER_FAILED',
    message: error instanceof Error ? error.message.slice(0, 2_000) : 'Worker failed' };
}

function delay(milliseconds: number) {
  return new Promise<void>((resolveDelay) => setTimeout(resolveDelay, milliseconds));
}
